language: generic

sudo: false

matrix:
  include:
    - { os: linux, env: PYTHON_VERSION=3.6 }
    - { os: linux, env: PYTHON_VERSION=3.7 }
    - { os: osx, env: PYTHON_VERSION=3.6 }
    - { os: osx, env: PYTHON_VERSION=3.7 }

env:
  global:
  - ENCRYPTION_LABEL: "fa70a735182b"
  - COMMIT_AUTHOR_EMAIL: "andrew.z.summers@gmail.com"

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install md5sha1sum; fi
  - source devtools/travis-ci/install_conda.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels omnia
  - conda config --add channels conda-forge
  - conda config --add channels mosdef
  - conda create -n test-environment python=$PYTHON_VERSION --file requirements-dev.txt
  - source activate test-environment
  - pip install -e .

script:
  - py.test -v --cov=foyer --cov-report= --pyargs foyer

after_success:
  - codecov
  - if [[ $PYTHON_VERSION == 3.6 ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source devtools/travis-ci/update_gh_pages.sh; fi
